version: '3'

services:
  api:
    build:
      context: .
    ports:
      - "7000:7000"
    volumes:
      - ".:/src"
    tty: true
    environment:
      TZ: Asia/Tokyo
      DEBUG: 1
    entrypoint: uvicorn app:app --host 0.0.0.0 --port 7000